export const topics = [
  // --- All Existing Categories ---
  {
    id: "arrays",
    name: "Arrays",
    questions: [
      {
        id: "a1",
        title: "Intersection of Two Arrays",
        url: "https://leetcode.com/problems/intersection-of-two-arrays/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "a2",
        title: "Move Zeroes",
        url: "https://leetcode.com/problems/move-zeroes/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "a3",
        title: "Sort an array 0's, 1's and 2's",
        url: "https://leetcode.com/problems/sort-colors/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "a4",
        title: "Segregate Even and Odd Numbers",
        url: "https://www.geeksforgeeks.org/problems/segregate-even-and-odd-numbers4629/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "a5",
        title: "Maximum Product Subarray",
        url: "https://leetcode.com/problems/maximum-product-subarray/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "a6",
        title: "Maximum Subarray",
        url: "https://leetcode.com/problems/maximum-subarray/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "a7",
        title: "Product of Array Except Self",
        url: "https://leetcode.com/problems/product-of-array-except-self/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "strings",
    name: "Strings",
    questions: [
      {
        id: "s1",
        title: "Multiply Strings",
        url: "https://leetcode.com/problems/multiply-strings",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "s2",
        title: "Add Strings",
        url: "https://leetcode.com/problems/add-strings/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "s3",
        title: "Add Binary",
        url: "https://leetcode.com/problems/add-binary/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "s4",
        title: "Reverse Words in a String III",
        url: "https://leetcode.com/problems/reverse-words-in-a-string-iii/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "s5",
        title: "Word with Maximum Frequency",
        url: "https://www.geeksforgeeks.org/problems/word-with-maximum-frequency0120/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "s6",
        title: "Remove All Occurrences of a Substring",
        url: "https://leetcode.com/problems/remove-all-occurrences-of-a-substring/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "s7",
        title: "Sort Vowels in a String",
        url: "https://leetcode.com/problems/sort-vowels-in-a-string/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "s8",
        title: "Reverse Words in a String",
        url: "https://leetcode.com/problems/reverse-words-in-a-string/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "linked-list",
    name: "Linked List",
    questions: [
      {
        id: "ll1",
        title: "Reverse Linked List",
        url: "https://leetcode.com/problems/reverse-linked-list/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "ll2",
        title: "Middle of the Linked List",
        url: "https://leetcode.com/problems/middle-of-the-linked-list/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "ll3",
        title: "Delete the Middle Node of a Linked List",
        url: "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "ll4",
        title: "Palindrome Linked List",
        url: "https://leetcode.com/problems/palindrome-linked-list/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "ll5",
        title: "Linked List Cycle",
        url: "https://leetcode.com/problems/linked-list-cycle/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "ll6",
        title: "Find Length of Loop",
        url: "https://www.geeksforgeeks.org/problems/find-length-of-loop/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "ll7",
        title: "Find the First Node of Loop in Linked List",
        url: "https://www.geeksforgeeks.org/problems/find-the-first-node-of-loop-in-linked-list--170645/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
    ],
  },
  {
    id: "sliding-window",
    name: "Sliding Window",
    questions: [
        {
            id: "sw1",
            title: "Max Sum of Distinct Subarrays",
            url: "https://leetcode.com/problems/maximum-sum-of-distinct-subarrays-with-length-k/",
            platform: "LeetCode",
            platformLogo: "/logos/leetcode.png",
        },
        {
            id: "sw2",
            title: "Find All Anagrams in a String",
            url: "https://leetcode.com/problems/find-all-anagrams-in-a-string/",
            platform: "LeetCode",
            platformLogo: "/logos/leetcode.png",
        },
        {
            id: "sw3",
            title: "Sliding Window Maximum",
            url: "https://leetcode.com/problems/sliding-window-maximum/",
            platform: "LeetCode",
            platformLogo: "/logos/leetcode.png",
        },
        {
            id: "sw4",
            title: "First Negative Integer in Window",
            url: "https://www.geeksforgeeks.org/problems/first-negative-integer-in-every-window-of-size-k3345/1",
            platform: "GFG",
            platformLogo: "/logos/gfg.png",
        },
        {
            id: "sw5",
            title: "Subarray Sum Equals K",
            url: "https://leetcode.com/problems/subarray-sum-equals-k/",
            platform: "LeetCode",
            platformLogo: "/logos/leetcode.png",
        },
        {
            id: "sw6",
            title: "Longest K Unique Characters Substring",
            url: "https://www.geeksforgeeks.org/problems/longest-k-unique-characters-substring0853/1",
            platform: "GFG",
            platformLogo: "/logos/gfg.png",
        },
        {
            id: "sw7",
            title: "Longest Substring Without Repeating Characters",
            url: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
            platform: "LeetCode",
            platformLogo: "/logos/leetcode.png",
        },
        {
            id: "sw8",
            title: "Subarray Product Less Than K",
            url: "https://leetcode.com/problems/subarray-product-less-than-k/",
            platform: "LeetCode",
            platformLogo: "/logos/leetcode.png",
        },
    ],
  },
  {
    id: "binary-search",
    name: "Binary Search",
    questions: [
      {
        id: "bs1",
        title: "Find Nth root of M",
        url: "https://www.geeksforgeeks.org/problems/find-nth-root-of-m5843/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "bs2",
        title: "Sqrt(x)",
        url: "https://leetcode.com/problems/sqrtx/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bs3",
        title: "Implement Upper Bound",
        url: "https://www.geeksforgeeks.org/problems/implement-upper-bound/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "bs4",
        title: "Implement Lower Bound",
        url: "https://www.geeksforgeeks.org/problems/implement-lower-bound/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "bs5",
        title: "Find First and Last Position of Element",
        url: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bs6",
        title: "Number of occurrence",
        url: "https://www.geeksforgeeks.org/problems/number-of-occurrence2259/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "bs7",
        title: "Search in Rotated Sorted Array",
        url: "https://leetcode.com/problems/search-in-rotated-sorted-array/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bs8",
        title: "Find Minimum in Rotated Sorted Array",
        url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bs9",
        title: "Koko Eating Bananas",
        url: "https://leetcode.com/problems/koko-eating-bananas/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bs10",
        title: "Minimum Number of Days to Make m Bouquets",
        url: "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bs11",
        title: "Capacity To Ship Packages Within D Days",
        url: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bs12",
        title: "Aggressive Cows",
        url: "https://www.geeksforgeeks.org/problems/aggressive-cows/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "bs13",
        title: "Allocate Minimum Number of Pages",
        url: "https://www.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "bs14",
        title: "Split Array Largest Sum",
        url: "https://leetcode.com/problems/split-array-largest-sum/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "hashing",
    name: "Hashing",
    questions: [
      {
        id: "h1",
        title: "Longest Consecutive Sequence",
        url: "https://leetcode.com/problems/longest-consecutive-sequence/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "h2",
        title: "Two Sum",
        url: "https://leetcode.com/problems/two-sum/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "h3",
        title: "Longest Subarray Sum  K",
        url: "https://www.geeksforgeeks.org/problems/longest-sub-array-with-sum-k0809/1",
        platform: "LeetCode",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "h4",
        title: "Count Subarrays with Given XOR K",
        url: "https://takeuforward.org/plus/dsa/problems/count-subarrays-with-given-xor-k",
        platform: "TakeUForward",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "h5",
        title: "Count Subarray with sum k",
        url: "https://www.geeksforgeeks.org/problems/subarrays-with-sum-k/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "h6",
        title: "Subarray Sums Divisible by K",
        url: "https://leetcode.com/problems/subarray-sums-divisible-by-k/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "sorting",
    name: "Sorting",
    questions: [
      {
        id: "so1",
        title: "Sort Array By Increasing Frequency",
        url: "https://leetcode.com/problems/sort-array-by-increasing-frequency/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "so2",
        title: "Relative Sort Array",
        url: "https://leetcode.com/problems/relative-sort-array/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "so3",
        title: "Custom Sort String",
        url: "https://leetcode.com/problems/custom-sort-string/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "so4",
        title: "Sort Characters By Frequency",
        url: "https://leetcode.com/problems/sort-characters-by-frequency/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "so5",
        title: "Sort Array By Parity",
        url: "https://leetcode.com/problems/sort-array-by-parity/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "2d-matrix",
    name: "2D Matrix",
    questions: [
      {
        id: "m1",
        title: "Search a 2D Matrix",
        url: "https://leetcode.com/problems/search-a-2d-matrix/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "m2",
        title: "Search a 2D Matrix II",
        url: "https://leetcode.com/problems/search-a-2d-matrix-ii/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "m3",
        title: "Rotate Image",
        url: "https://leetcode.com/problems/rotate-image/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "m4",
        title: "Pascal's Triangle",
        url: "https://leetcode.com/problems/pascals-triangle/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "m5",
        title: "Pascal's Triangle II",
        url: "https://leetcode.com/problems/pascals-triangle-ii/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "m6",
        title: "Sort the Matrix Diagonally",
        url: "https://leetcode.com/problems/sort-the-matrix-diagonally/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "m7",
        title: "Diagonal Traverse",
        url: "https://leetcode.com/problems/diagonal-traverse/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "m8",
        title: "Diagonal Traverse II",
        url: "https://leetcode.com/problems/diagonal-traverse-ii/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "tree",
    name: "Tree",
    questions: [
      {
        id: "t1",
        title: "Maximum Depth of Binary Tree",
        url: "https://leetcode.com/problems/maximum-depth-of-binary-tree/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "t2",
        title: "Balanced Binary Tree",
        url: "https://leetcode.com/problems/balanced-binary-tree/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "t3",
        title: "Diameter of Binary Tree",
        url: "https://leetcode.com/problems/diameter-of-binary-tree/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "t4",
        title: "Binary Tree Maximum Path Sum",
        url: "https://leetcode.com/problems/binary-tree-maximum-path-sum/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "t5",
        title: "Same Tree",
        url: "https://leetcode.com/problems/same-tree/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "t6",
        title: "Lowest Common Ancestor of a Binary Tree",
        url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "t7",
        title: "Search in a Binary Search Tree",
        url: "https://leetcode.com/problems/search-in-a-binary-search-tree/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "t8",
        title: "Validate Binary Search Tree",
        url: "https://leetcode.com/problems/validate-binary-search-tree/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "graph",
    name: "Graph",
    questions: [
      {
        id: "g1",
        title: "Number of Islands",
        url: "https://leetcode.com/problems/number-of-islands/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "g2",
        title: "Clone Graph",
        url: "https://leetcode.com/problems/clone-graph/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "g3",
        title: "Course Schedule",
        url: "https://leetcode.com/problems/course-schedule/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "dp",
    name: "DP",
    questions: [
      {
        id: "dp1",
        title: "Fibonacci Number",
        url: "https://leetcode.com/problems/fibonacci-number/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp2",
        title: "Climbing Stairs",
        url: "https://leetcode.com/problems/climbing-stairs/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp3",
        title: "Geek Jump",
        url: "https://www.geeksforgeeks.org/problems/geek-jump/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "dp4",
        title: "Frog Jump with k Distances",
        url: "https://takeuforward.org/plus/dsa/problems/frog-jump-with-k-distances",
        platform: "TakeUForward",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "dp5",
        title: "Maximum sum of non-adjacent elements",
        url: "https://leetcode.com/problems/house-robber/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp6",
        title: "House Robber II",
        url: "https://leetcode.com/problems/house-robber-ii/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp7",
        title: "Unique Paths",
        url: "https://leetcode.com/problems/unique-paths/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp8",
        title: "Unique Paths II",
        url: "https://leetcode.com/problems/unique-paths-ii/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp9",
        title: "Minimum Path Sum",
        url: "https://leetcode.com/problems/minimum-path-sum/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp10",
        title: "Minimum Path Sum in Triangular Grid",
        url: "https://takeuforward.org/data-structure/minimum-path-sum-in-triangular-grid-dp-11/",
        platform: "TakeUForward",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "dp11",
        title: "Subset sum equal to target",
        url: "https://www.geeksforgeeks.org/problems/subset-sum-problem-1611555638/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "dp12",
        title: "Partition Equal Subset Sum",
        url: "https://leetcode.com/problems/partition-equal-subset-sum/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp13",
        title: "Count Subsets with Sum K",
        url: "https://www.geeksforgeeks.org/problems/perfect-sum-problem5633/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "dp14",
        title: "Count Partitions with Given Difference",
        url: "https://www.geeksforgeeks.org/problems/partitions-with-given-difference/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "dp15",
        title: "0/1 Knapsack Problem",
        url: "https://www.geeksforgeeks.org/problems/0-1-knapsack-problem0945/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "dp16",
        title: "Minimum coin change problem",
        url: "https://leetcode.com/problems/coin-change/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp17",
        title: "Target Sum",
        url: "https://leetcode.com/problems/target-sum/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp18",
        title: "Unbound knapsack",
        url: "https://www.geeksforgeeks.org/problems/knapsack-with-duplicate-items4201/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "dp19",
        title: "Longest Common Subsequence",
        url: "https://leetcode.com/problems/longest-common-subsequence/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp20",
        title: "Longest Palindromic Subsequence",
        url: "https://leetcode.com/problems/longest-palindromic-subsequence/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp21",
        title: "Minimum Insertion Steps to Make a String Palindrome",
        url: "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp22",
        title: "Delete Operation for Two Strings",
        url: "https://leetcode.com/problems/delete-operation-for-two-strings/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp23",
        title: "Best Time to Buy and Sell Stock",
        url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp24",
        title: "Best Time to Buy and Sell Stock II",
        url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp25",
        title: "Best Time to Buy and Sell Stock III",
        url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp26",
        title: "Best Time to Buy and Sell Stock IV",
        url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp27",
        title: "Best Time to Buy and Sell Stock with Cooldown",
        url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "dp28",
        title: "Best Time to Buy and Sell Stock with Transaction Fee",
        url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "number-theory",
    name: "Number Theory",
    questions: [
      {
        id: "nt1",
        title: "Count Primes",
        url: "https://leetcode.com/problems/count-primes/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "nt2",
        title: "Sum of all divisors from 1 to n",
        url: "https://www.geeksforgeeks.org/problems/sum-of-all-divisors-from-1-to-n4738/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "nt3",
        title: "Largest prime factor",
        url: "https://www.geeksforgeeks.org/problems/largest-prime-factor2601/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "nt4",
        title: "Pow(x, n)",
        url: "https://leetcode.com/problems/powx-n/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "nt5",
        title: "Big Mod (UVA - 374)",
        url: "https://vjudge.net/problem/UVA-374",
        platform: "VJudge",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "nt6",
        title: "Combinations",
        url: "https://lightoj.com/problem/combinations",
        platform: "LightOJ",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "nt7",
        title: "All Divisors of a Number",
        url: "https://www.geeksforgeeks.org/problems/all-divisors-of-a-number/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "nt8",
        title: "Sum of all divisors from 1 to n",
        url: "https://www.geeksforgeeks.org/problems/sum-of-all-divisors-from-1-to-n4738/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "nt9",
        title: "Find Greatest Common Divisor of Array",
        url: "https://leetcode.com/problems/find-greatest-common-divisor-of-array/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "nt10",
        title: "LCM of two numbers",
        url: "https://www.geeksforgeeks.org/problems/lcm-of-two-numbers/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "nt11",
        title: "Common Divisors",
        url: "https://www.geeksforgeeks.org/problems/common-divisors4712/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "nt12",
        title: "Add Digits",
        url: "https://leetcode.com/problems/add-digits/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "backtracking",
    name: "Backtracking",
    questions: [
      {
        id: "bt1",
        title: "Subsets",
        url: "https://leetcode.com/problems/subsets",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bt2",
        title: "Subsets II",
        url: "https://leetcode.com/problems/subsets-ii",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bt3",
        title: "Permutations",
        url: "https://leetcode.com/problems/permutations",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bt4",
        title: "Permutations II",
        url: "https://leetcode.com/problems/permutations-ii",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bt5",
        title: "Combinations",
        url: "https://leetcode.com/problems/combinations",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bt6",
        title: "Combination Sum",
        url: "https://leetcode.com/problems/combination-sum",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bt7",
        title: "Combination Sum II",
        url: "https://leetcode.com/problems/combination-sum-ii",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bt8",
        title: "Combination Sum III",
        url: "https://leetcode.com/problems/combination-sum-iii",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bt9",
        title: "Combination Sum IV",
        url: "https://leetcode.com/problems/combination-sum-iv",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "bt10",
        title: "Letter Combinations of a Phone Number",
        url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  {
    id: "heap",
    name: "Heap",
    questions: [
      {
        id: "hp1",
        title: "Top K Frequent Elements",
        url: "https://leetcode.com/problems/top-k-frequent-elements/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "hp2",
        title: "Kth Largest Element in a Stream",
        url: "https://leetcode.com/problems/kth-largest-element-in-a-stream/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "hp3",
        title: "K Closest Points to Origin",
        url: "https://leetcode.com/problems/k-closest-points-to-origin/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "hp4",
        title: "Kth Largest Element in an Array",
        url: "https://leetcode.com/problems/kth-largest-element-in-an-array/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
  
  // --- NEW STL CATEGORY ---
  {
    id: "stl",
    name: "STL",
    questions: [
      {
        id: "stl1",
        title: "Reverse First K elements of Queue",
        url: "https://www.geeksforgeeks.org/problems/reverse-first-k-elements-of-queue/1",
        platform: "GFG",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "stl2",
        title: "Remove All Adjacent Duplicates In String",
        url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "stl3",
        title: "Balanced Brackets",
        url: "https://www.hackerearth.com/practice/algorithms/string-algorithm/string-searching/practice-problems/approximate/balance-brackets-f05b6f2c/",
        platform: "HackerEarth",
        platformLogo: "/logos/gfg.png",
      },
      {
        id: "stl4",
        title: "Implement Queue using Stacks",
        url: "https://leetcode.com/problems/implement-queue-using-stacks/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "stl5",
        title: "Implement Stack using Queues",
        url: "https://leetcode.com/problems/implement-stack-using-queues/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "stl6",
        title: "Next Greater Element I",
        url: "https://leetcode.com/problems/next-greater-element-i/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
      {
        id: "stl7",
        title: "Next Greater Element II",
        url: "https://leetcode.com/problems/next-greater-element-ii/description/",
        platform: "LeetCode",
        platformLogo: "/logos/leetcode.png",
      },
    ],
  },
];

// This function automatically collects all questions from every topic.
export const getAllQuestions = () =>
  topics.flatMap(t => t.questions);